/**
 * Generated by the Supabase MCP `generate_typescript_types` tool against the
 * portal project. DO NOT EDIT BY HAND — regenerate after every migration:
 *
 *   supabase gen types typescript --project-id <ref> > src/types/database.types.ts
 *
 * Note: only the `public` schema is present. `erp` IS exposed to PostgREST,
 * but `generate_typescript_types` still emits only the default schema, so
 * `erp` reads stay typed by hand in src/types/erp.ts. Regenerate with the CLI
 * and `--schema erp` if you want them generated.
 *
 * Last regenerated after migration 022 against dev — no hand edits. Covers
 * account_signals and score_settings (019), recommendations.score /
 * score_factors (020), and ai_summaries.headline (021).
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.15"
  }
  public: {
    Tables: {
      account_assignments: {
        Row: {
          access: string
          assigned_by: string | null
          created_at: string
          customer_key: string
          id: number
          user_id: string
        }
        Insert: {
          access?: string
          assigned_by?: string | null
          created_at?: string
          customer_key: string
          id?: never
          user_id: string
        }
        Update: {
          access?: string
          assigned_by?: string | null
          created_at?: string
          customer_key?: string
          id?: never
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "account_assignments_assigned_by_fkey"
            columns: ["assigned_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_assignments_assigned_by_fkey"
            columns: ["assigned_by"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_assignments_assigned_by_fkey"
            columns: ["assigned_by"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_assignments_assigned_by_fkey"
            columns: ["assigned_by"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_assignments_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_assignments_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_assignments_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_assignments_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
        ]
      }
      account_deactivations: {
        Row: {
          customer_key: string
          deactivated_at: string
          deactivated_by: string
          id: number
          note: string | null
          reactivated_at: string | null
          reactivated_by: string | null
          reason: string
        }
        Insert: {
          customer_key: string
          deactivated_at?: string
          deactivated_by?: string
          id?: never
          note?: string | null
          reactivated_at?: string | null
          reactivated_by?: string | null
          reason: string
        }
        Update: {
          customer_key?: string
          deactivated_at?: string
          deactivated_by?: string
          id?: never
          note?: string | null
          reactivated_at?: string | null
          reactivated_by?: string | null
          reason?: string
        }
        Relationships: [
          {
            foreignKeyName: "account_deactivations_deactivated_by_fkey"
            columns: ["deactivated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_deactivations_deactivated_by_fkey"
            columns: ["deactivated_by"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_deactivations_deactivated_by_fkey"
            columns: ["deactivated_by"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_deactivations_deactivated_by_fkey"
            columns: ["deactivated_by"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_deactivations_reactivated_by_fkey"
            columns: ["reactivated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_deactivations_reactivated_by_fkey"
            columns: ["reactivated_by"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_deactivations_reactivated_by_fkey"
            columns: ["reactivated_by"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_deactivations_reactivated_by_fkey"
            columns: ["reactivated_by"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
        ]
      }
      account_goals: {
        Row: {
          created_at: string
          created_by: string
          customer_key: string
          id: number
          note: string | null
          period_year: number
          target_amount: number
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          created_at?: string
          created_by?: string
          customer_key: string
          id?: never
          note?: string | null
          period_year: number
          target_amount: number
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          created_at?: string
          created_by?: string
          customer_key?: string
          id?: never
          note?: string | null
          period_year?: number
          target_amount?: number
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "account_goals_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_goals_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_goals_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_goals_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_goals_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_goals_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_goals_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_goals_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
        ]
      }
      account_signals: {
        Row: {
          cadence_confident: boolean
          cadence_days: number | null
          computed_at: string
          customer_key: string
          days_since_order: number | null
          days_since_touch: number | null
          factors: Json | null
          families_12m: number | null
          families_dropped: number | null
          families_prior_12m: number | null
          last_false_positive_at: string | null
          last_order_date: string | null
          last_order_received_at: string | null
          last_touch_date: string | null
          open_backlog_amount: number | null
          order_days_24m: number | null
          priority: string | null
          revenue_12m: number | null
          revenue_percentile: number | null
          revenue_prior_12m: number | null
          score: number | null
          score_cadence: number | null
          score_mix: number | null
          score_recency: number | null
          score_trend: number | null
          score_value: number | null
          scored_at: string | null
          yearly_sales_goal: number | null
          yoy_change: number | null
        }
        Insert: {
          cadence_confident?: boolean
          cadence_days?: number | null
          computed_at?: string
          customer_key: string
          days_since_order?: number | null
          days_since_touch?: number | null
          factors?: Json | null
          families_12m?: number | null
          families_dropped?: number | null
          families_prior_12m?: number | null
          last_false_positive_at?: string | null
          last_order_date?: string | null
          last_order_received_at?: string | null
          last_touch_date?: string | null
          open_backlog_amount?: number | null
          order_days_24m?: number | null
          priority?: string | null
          revenue_12m?: number | null
          revenue_percentile?: number | null
          revenue_prior_12m?: number | null
          score?: number | null
          score_cadence?: number | null
          score_mix?: number | null
          score_recency?: number | null
          score_trend?: number | null
          score_value?: number | null
          scored_at?: string | null
          yearly_sales_goal?: number | null
          yoy_change?: number | null
        }
        Update: {
          cadence_confident?: boolean
          cadence_days?: number | null
          computed_at?: string
          customer_key?: string
          days_since_order?: number | null
          days_since_touch?: number | null
          factors?: Json | null
          families_12m?: number | null
          families_dropped?: number | null
          families_prior_12m?: number | null
          last_false_positive_at?: string | null
          last_order_date?: string | null
          last_order_received_at?: string | null
          last_touch_date?: string | null
          open_backlog_amount?: number | null
          order_days_24m?: number | null
          priority?: string | null
          revenue_12m?: number | null
          revenue_percentile?: number | null
          revenue_prior_12m?: number | null
          score?: number | null
          score_cadence?: number | null
          score_mix?: number | null
          score_recency?: number | null
          score_trend?: number | null
          score_value?: number | null
          scored_at?: string | null
          yearly_sales_goal?: number | null
          yoy_change?: number | null
        }
        Relationships: []
      }
      actions: {
        Row: {
          action_date: string
          action_type: string
          created_at: string
          customer_key: string
          id: number
          note: string | null
          recommendation_id: number | null
          user_id: string
        }
        Insert: {
          action_date?: string
          action_type: string
          created_at?: string
          customer_key: string
          id?: never
          note?: string | null
          recommendation_id?: number | null
          user_id?: string
        }
        Update: {
          action_date?: string
          action_type?: string
          created_at?: string
          customer_key?: string
          id?: never
          note?: string | null
          recommendation_id?: number | null
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "actions_recommendation_id_fkey"
            columns: ["recommendation_id"]
            isOneToOne: false
            referencedRelation: "recommendations"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "actions_recommendation_id_fkey"
            columns: ["recommendation_id"]
            isOneToOne: false
            referencedRelation: "v_mission_detail"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "actions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "actions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "actions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "actions_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
        ]
      }
      ai_briefs: {
        Row: {
          action: string
          content: string
          context_hash: string | null
          generated_at: string
          model: string | null
          prompt_version: string | null
          subject_key: string
          user_id: string
        }
        Insert: {
          action: string
          content: string
          context_hash?: string | null
          generated_at?: string
          model?: string | null
          prompt_version?: string | null
          subject_key?: string
          user_id: string
        }
        Update: {
          action?: string
          content?: string
          context_hash?: string | null
          generated_at?: string
          model?: string | null
          prompt_version?: string | null
          subject_key?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_briefs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "ai_briefs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "ai_briefs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "ai_briefs_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
        ]
      }
      ai_summaries: {
        Row: {
          content: string
          context_hash: string | null
          customer_key: string
          generated_at: string
          generated_by: string | null
          headline: string | null
          model: string | null
          prompt_version: string | null
        }
        Insert: {
          content: string
          context_hash?: string | null
          customer_key: string
          generated_at?: string
          generated_by?: string | null
          headline?: string | null
          model?: string | null
          prompt_version?: string | null
        }
        Update: {
          content?: string
          context_hash?: string | null
          customer_key?: string
          generated_at?: string
          generated_by?: string | null
          headline?: string | null
          model?: string | null
          prompt_version?: string | null
        }
        Relationships: [
          {
            foreignKeyName: "ai_summaries_generated_by_fkey"
            columns: ["generated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "ai_summaries_generated_by_fkey"
            columns: ["generated_by"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "ai_summaries_generated_by_fkey"
            columns: ["generated_by"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "ai_summaries_generated_by_fkey"
            columns: ["generated_by"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
        ]
      }
      ai_usage_events: {
        Row: {
          action: string
          created_at: string
          id: number
          user_id: string
        }
        Insert: {
          action: string
          created_at?: string
          id?: never
          user_id: string
        }
        Update: {
          action?: string
          created_at?: string
          id?: never
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "ai_usage_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "ai_usage_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "ai_usage_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "ai_usage_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
        ]
      }
      app_settings: {
        Row: {
          description: string | null
          enabled: boolean
          params: Json
          setting_key: string
          updated_at: string
          updated_by: string | null
        }
        Insert: {
          description?: string | null
          enabled?: boolean
          params?: Json
          setting_key: string
          updated_at?: string
          updated_by?: string | null
        }
        Update: {
          description?: string | null
          enabled?: boolean
          params?: Json
          setting_key?: string
          updated_at?: string
          updated_by?: string | null
        }
        Relationships: []
      }
      contacts: {
        Row: {
          created_at: string
          created_by: string
          customer_key: string
          email: string | null
          id: number
          is_primary: boolean
          name: string
          notes: string | null
          phone: string | null
          title: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string
          customer_key: string
          email?: string | null
          id?: never
          is_primary?: boolean
          name: string
          notes?: string | null
          phone?: string | null
          title?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string
          customer_key?: string
          email?: string | null
          id?: never
          is_primary?: boolean
          name?: string
          notes?: string | null
          phone?: string | null
          title?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "contacts_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "contacts_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "contacts_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "contacts_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
        ]
      }
      job_runs: {
        Row: {
          error: string | null
          finished_at: string | null
          id: number
          job_name: string
          rows_affected: number | null
          started_at: string
          status: string
        }
        Insert: {
          error?: string | null
          finished_at?: string | null
          id?: never
          job_name: string
          rows_affected?: number | null
          started_at?: string
          status?: string
        }
        Update: {
          error?: string | null
          finished_at?: string | null
          id?: never
          job_name?: string
          rows_affected?: number | null
          started_at?: string
          status?: string
        }
        Relationships: []
      }
      login_events: {
        Row: {
          id: number
          logged_at: string
          user_id: string
        }
        Insert: {
          id?: never
          logged_at?: string
          user_id: string
        }
        Update: {
          id?: never
          logged_at?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "login_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "login_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "login_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "login_events_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
        ]
      }
      mission_batches: {
        Row: {
          created_at: string
          created_by: string
          description: string | null
          due_date: string | null
          id: number
          requires_visit: boolean
          scope_type: string
          scope_value: string | null
          title: string
        }
        Insert: {
          created_at?: string
          created_by: string
          description?: string | null
          due_date?: string | null
          id?: never
          requires_visit?: boolean
          scope_type: string
          scope_value?: string | null
          title: string
        }
        Update: {
          created_at?: string
          created_by?: string
          description?: string | null
          due_date?: string | null
          id?: never
          requires_visit?: boolean
          scope_type?: string
          scope_value?: string | null
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "mission_batches_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "mission_batches_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "mission_batches_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "mission_batches_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
        ]
      }
      notes: {
        Row: {
          body: string
          created_at: string
          created_by: string
          customer_key: string
          id: number
        }
        Insert: {
          body: string
          created_at?: string
          created_by?: string
          customer_key: string
          id?: never
        }
        Update: {
          body?: string
          created_at?: string
          created_by?: string
          customer_key?: string
          id?: never
        }
        Relationships: [
          {
            foreignKeyName: "notes_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "notes_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "notes_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "notes_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
        ]
      }
      photos: {
        Row: {
          caption: string | null
          category: string | null
          created_at: string
          created_by: string
          customer_key: string
          id: number
          storage_path: string
          visit_id: number | null
        }
        Insert: {
          caption?: string | null
          category?: string | null
          created_at?: string
          created_by?: string
          customer_key: string
          id?: never
          storage_path: string
          visit_id?: number | null
        }
        Update: {
          caption?: string | null
          category?: string | null
          created_at?: string
          created_by?: string
          customer_key?: string
          id?: never
          storage_path?: string
          visit_id?: number | null
        }
        Relationships: [
          {
            foreignKeyName: "photos_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "photos_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "photos_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "photos_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "photos_visit_id_fkey"
            columns: ["visit_id"]
            isOneToOne: false
            referencedRelation: "visits"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          active: boolean
          created_at: string
          email: string | null
          full_name: string
          rep_group_vendor_id: string | null
          role: string
          sales_rep_key: string | null
          user_id: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          email?: string | null
          full_name?: string
          rep_group_vendor_id?: string | null
          role?: string
          sales_rep_key?: string | null
          user_id: string
        }
        Update: {
          active?: boolean
          created_at?: string
          email?: string | null
          full_name?: string
          rep_group_vendor_id?: string | null
          role?: string
          sales_rep_key?: string | null
          user_id?: string
        }
        Relationships: []
      }
      recommendations: {
        Row: {
          batch_id: number | null
          closed_at: string | null
          closed_by: string | null
          created_at: string
          created_by: string | null
          customer_key: string
          due_date: string | null
          id: number
          outcome: string | null
          outcome_note: string | null
          priority: string
          reason: string | null
          requires_visit: boolean
          rule_key: string | null
          score: number | null
          score_factors: Json | null
          source: string
          status: string
          title: string
        }
        Insert: {
          batch_id?: number | null
          closed_at?: string | null
          closed_by?: string | null
          created_at?: string
          created_by?: string | null
          customer_key: string
          due_date?: string | null
          id?: never
          outcome?: string | null
          outcome_note?: string | null
          priority?: string
          reason?: string | null
          requires_visit?: boolean
          rule_key?: string | null
          score?: number | null
          score_factors?: Json | null
          source?: string
          status?: string
          title: string
        }
        Update: {
          batch_id?: number | null
          closed_at?: string | null
          closed_by?: string | null
          created_at?: string
          created_by?: string | null
          customer_key?: string
          due_date?: string | null
          id?: never
          outcome?: string | null
          outcome_note?: string | null
          priority?: string
          reason?: string | null
          requires_visit?: boolean
          rule_key?: string | null
          score?: number | null
          score_factors?: Json | null
          source?: string
          status?: string
          title?: string
        }
        Relationships: [
          {
            foreignKeyName: "recommendations_batch_id_fkey"
            columns: ["batch_id"]
            isOneToOne: false
            referencedRelation: "mission_batch_progress"
            referencedColumns: ["batch_id"]
          },
          {
            foreignKeyName: "recommendations_batch_id_fkey"
            columns: ["batch_id"]
            isOneToOne: false
            referencedRelation: "mission_batches"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "recommendations_closed_by_fkey"
            columns: ["closed_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "recommendations_closed_by_fkey"
            columns: ["closed_by"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "recommendations_closed_by_fkey"
            columns: ["closed_by"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "recommendations_closed_by_fkey"
            columns: ["closed_by"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "recommendations_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "recommendations_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "recommendations_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "recommendations_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "recommendations_rule_key_fkey"
            columns: ["rule_key"]
            isOneToOne: false
            referencedRelation: "rule_settings"
            referencedColumns: ["rule_key"]
          },
        ]
      }
      rule_settings: {
        Row: {
          description: string
          enabled: boolean
          params: Json
          rule_key: string
          updated_at: string
        }
        Insert: {
          description: string
          enabled?: boolean
          params?: Json
          rule_key: string
          updated_at?: string
        }
        Update: {
          description?: string
          enabled?: boolean
          params?: Json
          rule_key?: string
          updated_at?: string
        }
        Relationships: []
      }
      score_settings: {
        Row: {
          id: boolean
          params: Json
          priority_high: number
          priority_low: number
          updated_at: string
          updated_by: string | null
          weights: Json
        }
        Insert: {
          id?: boolean
          params?: Json
          priority_high?: number
          priority_low?: number
          updated_at?: string
          updated_by?: string | null
          weights?: Json
        }
        Update: {
          id?: boolean
          params?: Json
          priority_high?: number
          priority_low?: number
          updated_at?: string
          updated_by?: string | null
          weights?: Json
        }
        Relationships: [
          {
            foreignKeyName: "score_settings_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "score_settings_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "score_settings_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "score_settings_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
        ]
      }
      tasks: {
        Row: {
          completed_at: string | null
          created_at: string
          customer_key: string | null
          due_date: string | null
          id: number
          status: string
          title: string
          user_id: string
        }
        Insert: {
          completed_at?: string | null
          created_at?: string
          customer_key?: string | null
          due_date?: string | null
          id?: never
          status?: string
          title: string
          user_id?: string
        }
        Update: {
          completed_at?: string | null
          created_at?: string
          customer_key?: string | null
          due_date?: string | null
          id?: never
          status?: string
          title?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tasks_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "tasks_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "tasks_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "tasks_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
        ]
      }
      visits: {
        Row: {
          action_id: number | null
          comments: string | null
          competition_seen: string[]
          competitor_promos: string | null
          created_at: string
          customer_key: string
          display_quality: number | null
          id: number
          inventory_level: string | null
          staff_knowledge: number | null
          store_condition: number | null
          store_traffic: string | null
          user_id: string
          visit_date: string
          visit_type: string
        }
        Insert: {
          action_id?: number | null
          comments?: string | null
          competition_seen?: string[]
          competitor_promos?: string | null
          created_at?: string
          customer_key: string
          display_quality?: number | null
          id?: never
          inventory_level?: string | null
          staff_knowledge?: number | null
          store_condition?: number | null
          store_traffic?: string | null
          user_id?: string
          visit_date?: string
          visit_type: string
        }
        Update: {
          action_id?: number | null
          comments?: string | null
          competition_seen?: string[]
          competitor_promos?: string | null
          created_at?: string
          customer_key?: string
          display_quality?: number | null
          id?: never
          inventory_level?: string | null
          staff_knowledge?: number | null
          store_condition?: number | null
          store_traffic?: string | null
          user_id?: string
          visit_date?: string
          visit_type?: string
        }
        Relationships: [
          {
            foreignKeyName: "visits_action_id_fkey"
            columns: ["action_id"]
            isOneToOne: false
            referencedRelation: "actions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "visits_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "visits_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "visits_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "visits_user_id_fkey"
            columns: ["user_id"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
        ]
      }
    }
    Views: {
      account_coverage: {
        Row: {
          contacted_last_30d: boolean | null
          contacted_last_90d: boolean | null
          customer_key: string | null
          last_contact_date: string | null
          rep_name: string | null
          user_id: string | null
        }
        Relationships: []
      }
      mission_batch_progress: {
        Row: {
          acted_count: number | null
          batch_id: number | null
          closed_count: number | null
          created_at: string | null
          created_by: string | null
          description: string | null
          dismissed_count: number | null
          due_date: string | null
          open_count: number | null
          overdue_count: number | null
          requires_visit: boolean | null
          scope_type: string | null
          scope_value: string | null
          title: string | null
          total: number | null
        }
        Relationships: [
          {
            foreignKeyName: "mission_batches_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "mission_batches_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "mission_batches_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "mission_batches_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
        ]
      }
      rep_execution_summary: {
        Row: {
          actions_last_30d: number | null
          active: boolean | null
          assigned_accounts: number | null
          full_name: string | null
          last_action_date: string | null
          last_login_at: string | null
          open_recommendations: number | null
          overdue_recommendations: number | null
          rep_group_vendor_id: string | null
          user_id: string | null
        }
        Insert: {
          actions_last_30d?: never
          active?: boolean | null
          assigned_accounts?: never
          full_name?: string | null
          last_action_date?: never
          last_login_at?: never
          open_recommendations?: never
          overdue_recommendations?: never
          rep_group_vendor_id?: string | null
          user_id?: string | null
        }
        Update: {
          actions_last_30d?: never
          active?: boolean | null
          assigned_accounts?: never
          full_name?: string | null
          last_action_date?: never
          last_login_at?: never
          open_recommendations?: never
          overdue_recommendations?: never
          rep_group_vendor_id?: string | null
          user_id?: string | null
        }
        Relationships: []
      }
      v_account_contacts: {
        Row: {
          contact_key: string | null
          customer_key: string | null
          email: string | null
          id: number | null
          is_primary: boolean | null
          name: string | null
          notes: string | null
          phone: string | null
          source: string | null
          title: string | null
          updated_at: string | null
        }
        Relationships: []
      }
      v_account_goal_progress: {
        Row: {
          active_flag: string | null
          as_of: string | null
          attainment_pct: number | null
          created_by: string | null
          customer_key: string | null
          customer_name: string | null
          days_elapsed: number | null
          days_remaining: number | null
          days_total: number | null
          erp_yearly_sales_goal: number | null
          expected_amount: number | null
          expected_pct: number | null
          gap_to_goal: number | null
          gap_to_pace: number | null
          goal_id: number | null
          note: string | null
          on_track: boolean | null
          pace_basis: string | null
          period_end: string | null
          period_start: string | null
          period_year: number | null
          projected_amount: number | null
          revenue_to_date: number | null
          sold_to_city: string | null
          sold_to_state: string | null
          target_amount: number | null
          updated_at: string | null
          updated_by: string | null
        }
        Relationships: [
          {
            foreignKeyName: "account_goals_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_goals_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_goals_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_goals_created_by_fkey"
            columns: ["created_by"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_goals_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_goals_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "rep_execution_summary"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_goals_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "v_rep_activity"
            referencedColumns: ["user_id"]
          },
          {
            foreignKeyName: "account_goals_updated_by_fkey"
            columns: ["updated_by"]
            isOneToOne: false
            referencedRelation: "v_rep_goal_attainment"
            referencedColumns: ["user_id"]
          },
        ]
      }
      v_account_list: {
        Row: {
          active_flag: string | null
          assigned_sales_rep_id: string | null
          assigned_sales_rep_name: string | null
          customer_key: string | null
          customer_name: string | null
          deactivated_at: string | null
          deactivation_reason: string | null
          last_order_date: string | null
          sold_to_city: string | null
          sold_to_state: string | null
          territory: string | null
        }
        Relationships: []
      }
      v_account_order_lines: {
        Row: {
          backlog_qty: number | null
          bookings: number | null
          customer_key: string | null
          is_backlog_line: boolean | null
          line_num: number | null
          line_status_desc: string | null
          order_date: string | null
          order_id: string | null
          order_qty: number | null
          part_description: string | null
          part_id: string | null
          part_key: string | null
          promise_date: string | null
        }
        Relationships: []
      }
      v_account_recent_order_headers: {
        Row: {
          backlog_amount: number | null
          backlog_qty: number | null
          bookings: number | null
          customer_key: string | null
          line_count: number | null
          next_promise_date: string | null
          open_line_count: number | null
          order_date: string | null
          order_id: string | null
          order_qty: number | null
          order_state: string | null
          order_status_desc: string | null
          rn: number | null
        }
        Relationships: []
      }
      v_account_recent_orders: {
        Row: {
          backlog_qty: number | null
          bookings: number | null
          customer_key: string | null
          is_backlog_line: boolean | null
          line_num: number | null
          line_status_desc: string | null
          order_date: string | null
          order_id: string | null
          order_qty: number | null
          order_state: string | null
          order_status_desc: string | null
          part_description: string | null
          part_id: string | null
          part_key: string | null
          promise_date: string | null
        }
        Relationships: []
      }
      v_account_recent_shipment_headers: {
        Row: {
          actual_delivery_date: string | null
          customer_key: string | null
          line_count: number | null
          order_ids: string | null
          packlist_id: string | null
          rn: number | null
          ship_date: string | null
          ship_via: string | null
          shipment_state: string | null
          shipped_qty: number | null
          shipped_revenue: number | null
          shipper_status_desc: string | null
          tracking_number: string | null
        }
        Relationships: []
      }
      v_account_recent_shipments: {
        Row: {
          actual_delivery_date: string | null
          customer_key: string | null
          invoice_id: string | null
          line_num: number | null
          order_id: string | null
          packlist_id: string | null
          part_description: string | null
          part_id: string | null
          part_key: string | null
          promise_date: string | null
          ship_date: string | null
          shipment_state: string | null
          shipped_qty: number | null
          shipped_revenue: number | null
          shipper_status_desc: string | null
        }
        Relationships: []
      }
      v_account_revenue_monthly: {
        Row: {
          customer_key: string | null
          invoice_count: number | null
          month: string | null
          revenue: number | null
        }
        Relationships: []
      }
      v_account_shipment_lines: {
        Row: {
          actual_delivery_date: string | null
          customer_key: string | null
          invoice_id: string | null
          line_num: number | null
          order_id: string | null
          packlist_id: string | null
          part_description: string | null
          part_id: string | null
          part_key: string | null
          ship_date: string | null
          shipped_qty: number | null
          shipped_revenue: number | null
          tracking_number: string | null
        }
        Relationships: []
      }
      v_account_summary: {
        Row: {
          backlog_qty: number | null
          customer_key: string | null
          last_invoice_date: string | null
          last_order_date: string | null
          open_order_count: number | null
          open_order_value: number | null
          revenue_prior_ytd: number | null
          revenue_trailing_12m: number | null
          revenue_ytd: number | null
        }
        Relationships: []
      }
      v_ats_list: {
        Row: {
          ats_qty: number | null
          availability_status: string | null
          backlog_qty: number | null
          barrel_length: string | null
          chambering: string | null
          committed_qty: number | null
          inbound_qty: number | null
          is_oversold: boolean | null
          loaded_at: string | null
          next_avail_date: string | null
          on_hand_qty: number | null
          part_description: string | null
          part_id: string | null
          part_key: string | null
          product_family: string | null
          upc: string | null
        }
        Relationships: []
      }
      v_backlog_by_sku: {
        Row: {
          backlog_amount: number | null
          backlog_qty: number | null
          chambering: string | null
          customer_id: string | null
          customer_key: string | null
          customer_name: string | null
          earliest_desired_ship_date: string | null
          earliest_promise_date: string | null
          latest_order_date: string | null
          open_line_count: number | null
          part_description: string | null
          part_id: string | null
          part_key: string | null
          product_family: string | null
        }
        Relationships: []
      }
      v_data_freshness: {
        Row: {
          data_loaded_at: string | null
          data_through: string | null
        }
        Relationships: []
      }
      v_mission_detail: {
        Row: {
          batch_id: number | null
          closed_at: string | null
          customer_key: string | null
          customer_name: string | null
          due_date: string | null
          id: number | null
          outcome: string | null
          outcome_note: string | null
          priority: string | null
          rep_names: string | null
          requires_visit: boolean | null
          status: string | null
          title: string | null
        }
        Relationships: [
          {
            foreignKeyName: "recommendations_batch_id_fkey"
            columns: ["batch_id"]
            isOneToOne: false
            referencedRelation: "mission_batch_progress"
            referencedColumns: ["batch_id"]
          },
          {
            foreignKeyName: "recommendations_batch_id_fkey"
            columns: ["batch_id"]
            isOneToOne: false
            referencedRelation: "mission_batches"
            referencedColumns: ["id"]
          },
        ]
      }
      v_my_goal_rollup: {
        Row: {
          accounts_behind: number | null
          accounts_with_goal: number | null
          attainment_pct: number | null
          expected_pct: number | null
          expected_total: number | null
          period_year: number | null
          revenue_total: number | null
          target_total: number | null
        }
        Relationships: []
      }
      v_rep_activity: {
        Row: {
          actions_30d: number | null
          active: boolean | null
          email: string | null
          full_name: string | null
          last_action_date: string | null
          last_login_at: string | null
          logins_30d: number | null
          open_missions: number | null
          overdue_missions: number | null
          sales_rep_key: string | null
          user_id: string | null
          vendor_id: string | null
        }
        Relationships: []
      }
      v_rep_goal_attainment: {
        Row: {
          accounts_behind: number | null
          accounts_with_goal: number | null
          active: boolean | null
          assigned_accounts: number | null
          attainment_pct: number | null
          expected_pct: number | null
          full_name: string | null
          period_year: number | null
          revenue_total: number | null
          target_total: number | null
          user_id: string | null
        }
        Relationships: []
      }
      v_sku_sales_by_account: {
        Row: {
          chambering: string | null
          customer_key: string | null
          invoice_count: number | null
          last_invoice_date: string | null
          part_description: string | null
          part_id: string | null
          part_key: string | null
          product_family: string | null
          qty: number | null
          revenue: number | null
          sales_year: number | null
          upc: string | null
        }
        Relationships: []
      }
      v_territory_account_yoy: {
        Row: {
          backlog_amount: number | null
          backlog_qty: number | null
          customer_key: string | null
          customer_name: string | null
          last_invoice_date: string | null
          open_order_value: number | null
          revenue_prior_ytd: number | null
          revenue_trailing_12m: number | null
          revenue_ytd: number | null
          sold_to_city: string | null
          sold_to_state: string | null
          yearly_sales_goal: number | null
        }
        Relationships: []
      }
      v_territory_recent_orders: {
        Row: {
          customer_key: string | null
          customer_name: string | null
          has_backlog: boolean | null
          line_count: number | null
          order_amount: number | null
          order_date: string | null
          order_id: string | null
        }
        Relationships: []
      }
      v_territory_sku_sales: {
        Row: {
          chambering: string | null
          invoice_count: number | null
          last_invoice_date: string | null
          part_description: string | null
          part_id: string | null
          part_key: string | null
          product_family: string | null
          qty: number | null
          revenue: number | null
          sales_year: number | null
          upc: string | null
        }
        Relationships: []
      }
      v_user_accounts: {
        Row: {
          customer_key: string | null
          user_id: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      admin_rescore_accounts: { Args: never; Returns: number }
      ai_batch_targets: {
        Args: { p_per_rep?: number }
        Returns: {
          customer_key: string
          score: number
        }[]
      }
      apply_account_scores: {
        Args: {
          p_settings?: Database["public"]["Tables"]["score_settings"]["Row"]
        }
        Returns: number
      }
      clamp100: { Args: { v: number }; Returns: number }
      create_mission: {
        Args: {
          p_active_only?: boolean
          p_customer_keys?: string[]
          p_dry_run?: boolean
          p_due_date?: string
          p_priority?: string
          p_reason?: string
          p_requires_visit?: boolean
          p_scope_type?: string
          p_scope_value?: string
          p_title: string
        }
        Returns: {
          batch_id: number
          created_count: number
        }[]
      }
      explain_score: { Args: { p_factors: Json }; Returns: string }
      generate_recommendations: {
        Args: never
        Returns: {
          out_created: number
          out_rule_key: string
        }[]
      }
      has_account_access: { Args: { p_customer_key: string }; Returns: boolean }
      is_admin: { Args: never; Returns: boolean }
      log_job_run: {
        Args: {
          p_error?: string
          p_job_name: string
          p_rows: number
          p_started_at?: string
          p_status: string
        }
        Returns: undefined
      }
      log_login: { Args: never; Returns: undefined }
      my_customer_keys: { Args: never; Returns: string[] }
      placeholder_rep_keys: { Args: never; Returns: string[] }
      preview_account_scores: {
        Args: {
          p_high?: number
          p_limit?: number
          p_low?: number
          p_params?: Json
          p_weights?: Json
        }
        Returns: {
          customer_key: string
          customer_name: string
          factors: Json
          priority: string
          score: number
          score_cadence: number
          score_mix: number
          score_recency: number
          score_trend: number
          score_value: number
        }[]
      }
      preview_recommendation_counts: {
        Args: {
          p_high?: number
          p_low?: number
          p_params?: Json
          p_rules?: Json
          p_weights?: Json
        }
        Returns: {
          rule_key: string
          would_create: number
        }[]
      }
      refresh_account_signals: { Args: never; Returns: number }
      refresh_territory_rollups: {
        Args: never
        Returns: {
          rollup_name: string
          row_count: number
        }[]
      }
      report_global_product_sales: {
        Args: { p_limit?: number; p_months?: number }
        Returns: {
          account_count: number
          barrel_length: string
          chambering: string
          invoice_count: number
          part_description: string
          part_id: string
          part_key: string
          product_code: string
          product_family: string
          qty: number
          revenue: number
        }[]
      }
      rule_in_cooldown: {
        Args: { p_customer_key: string; p_params: Json; p_rule_key: string }
        Returns: boolean
      }
      score_account: {
        Args: {
          cfg: Database["public"]["Tables"]["score_settings"]["Row"]
          s: Database["public"]["Tables"]["account_signals"]["Row"]
        }
        Returns: Json
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
