/**
 * Generated by the Supabase MCP `generate_typescript_types` tool against the
 * portal project. DO NOT EDIT BY HAND — regenerate after every migration:
 *
 *   supabase gen types typescript --project-id <ref> > src/types/database.types.ts
 *
 * Note: only the `public` schema is present. `erp` IS exposed to PostgREST,
 * but `generate_typescript_types` still emits only the default schema, so
 * `erp` reads stay typed by hand in src/types/erp.ts. Regenerate with the CLI
 * and `--schema erp` if you want them generated.
 *
 * Last regenerated after migration 014; hand-extended for 016 (missions,
 * profiles.email) — regenerate when database access is available and diff
 * against this file.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: '14.15'
  }
  public: {
    Tables: {
      account_assignments: {
        Row: {
          access: string
          assigned_by: string | null
          created_at: string
          customer_key: string
          id: number
          user_id: string
        }
        Insert: {
          access?: string
          assigned_by?: string | null
          created_at?: string
          customer_key: string
          id?: never
          user_id: string
        }
        Update: {
          access?: string
          assigned_by?: string | null
          created_at?: string
          customer_key?: string
          id?: never
          user_id?: string
        }
        Relationships: []
      }
      actions: {
        Row: {
          action_date: string
          action_type: string
          created_at: string
          customer_key: string
          id: number
          note: string | null
          recommendation_id: number | null
          user_id: string
        }
        Insert: {
          action_date?: string
          action_type: string
          created_at?: string
          customer_key: string
          id?: never
          note?: string | null
          recommendation_id?: number | null
          user_id?: string
        }
        Update: {
          action_date?: string
          action_type?: string
          created_at?: string
          customer_key?: string
          id?: never
          note?: string | null
          recommendation_id?: number | null
          user_id?: string
        }
        Relationships: []
      }
      ai_summaries: {
        Row: {
          content: string
          context_hash: string | null
          customer_key: string
          generated_at: string
          generated_by: string | null
          model: string | null
          prompt_version: string | null
        }
        Insert: {
          content: string
          context_hash?: string | null
          customer_key: string
          generated_at?: string
          generated_by?: string | null
          model?: string | null
          prompt_version?: string | null
        }
        Update: {
          content?: string
          context_hash?: string | null
          customer_key?: string
          generated_at?: string
          generated_by?: string | null
          model?: string | null
          prompt_version?: string | null
        }
        Relationships: []
      }
      contacts: {
        Row: {
          created_at: string
          created_by: string
          customer_key: string
          email: string | null
          id: number
          is_primary: boolean
          name: string
          notes: string | null
          phone: string | null
          title: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string
          customer_key: string
          email?: string | null
          id?: never
          is_primary?: boolean
          name: string
          notes?: string | null
          phone?: string | null
          title?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string
          customer_key?: string
          email?: string | null
          id?: never
          is_primary?: boolean
          name?: string
          notes?: string | null
          phone?: string | null
          title?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      job_runs: {
        Row: {
          error: string | null
          finished_at: string | null
          id: number
          job_name: string
          rows_affected: number | null
          started_at: string
          status: string
        }
        Insert: {
          error?: string | null
          finished_at?: string | null
          id?: never
          job_name: string
          rows_affected?: number | null
          started_at?: string
          status?: string
        }
        Update: {
          error?: string | null
          finished_at?: string | null
          id?: never
          job_name?: string
          rows_affected?: number | null
          started_at?: string
          status?: string
        }
        Relationships: []
      }
      login_events: {
        Row: {
          id: number
          logged_at: string
          user_id: string
        }
        Insert: {
          id?: never
          logged_at?: string
          user_id: string
        }
        Update: {
          id?: never
          logged_at?: string
          user_id?: string
        }
        Relationships: []
      }
      mission_batches: {
        Row: {
          created_at: string
          created_by: string
          description: string | null
          due_date: string | null
          id: number
          requires_visit: boolean
          scope_type: string
          scope_value: string | null
          title: string
        }
        Insert: {
          created_at?: string
          created_by: string
          description?: string | null
          due_date?: string | null
          id?: never
          requires_visit?: boolean
          scope_type: string
          scope_value?: string | null
          title: string
        }
        Update: {
          created_at?: string
          created_by?: string
          description?: string | null
          due_date?: string | null
          id?: never
          requires_visit?: boolean
          scope_type?: string
          scope_value?: string | null
          title?: string
        }
        Relationships: []
      }
      notes: {
        Row: {
          body: string
          created_at: string
          created_by: string
          customer_key: string
          id: number
        }
        Insert: {
          body: string
          created_at?: string
          created_by?: string
          customer_key: string
          id?: never
        }
        Update: {
          body?: string
          created_at?: string
          created_by?: string
          customer_key?: string
          id?: never
        }
        Relationships: []
      }
      photos: {
        Row: {
          caption: string | null
          category: string | null
          created_at: string
          created_by: string
          customer_key: string
          id: number
          storage_path: string
          visit_id: number | null
        }
        Insert: {
          caption?: string | null
          category?: string | null
          created_at?: string
          created_by?: string
          customer_key: string
          id?: never
          storage_path: string
          visit_id?: number | null
        }
        Update: {
          caption?: string | null
          category?: string | null
          created_at?: string
          created_by?: string
          customer_key?: string
          id?: never
          storage_path?: string
          visit_id?: number | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          active: boolean
          created_at: string
          email: string | null
          full_name: string
          rep_group_vendor_id: string | null
          role: string
          sales_rep_key: string | null
          user_id: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          email?: string | null
          full_name?: string
          rep_group_vendor_id?: string | null
          role?: string
          sales_rep_key?: string | null
          user_id: string
        }
        Update: {
          active?: boolean
          created_at?: string
          email?: string | null
          full_name?: string
          rep_group_vendor_id?: string | null
          role?: string
          sales_rep_key?: string | null
          user_id?: string
        }
        Relationships: []
      }
      recommendations: {
        Row: {
          batch_id: number | null
          closed_at: string | null
          closed_by: string | null
          created_at: string
          created_by: string | null
          customer_key: string
          due_date: string | null
          id: number
          outcome: string | null
          outcome_note: string | null
          priority: string
          reason: string | null
          requires_visit: boolean
          rule_key: string | null
          source: string
          status: string
          title: string
        }
        Insert: {
          batch_id?: number | null
          closed_at?: string | null
          closed_by?: string | null
          created_at?: string
          created_by?: string | null
          customer_key: string
          due_date?: string | null
          id?: never
          outcome?: string | null
          outcome_note?: string | null
          priority?: string
          reason?: string | null
          requires_visit?: boolean
          rule_key?: string | null
          source?: string
          status?: string
          title: string
        }
        Update: {
          batch_id?: number | null
          closed_at?: string | null
          closed_by?: string | null
          created_at?: string
          created_by?: string | null
          customer_key?: string
          due_date?: string | null
          id?: never
          outcome?: string | null
          outcome_note?: string | null
          priority?: string
          reason?: string | null
          requires_visit?: boolean
          rule_key?: string | null
          source?: string
          status?: string
          title?: string
        }
        Relationships: []
      }
      rule_settings: {
        Row: {
          description: string
          enabled: boolean
          params: Json
          rule_key: string
          updated_at: string
        }
        Insert: {
          description: string
          enabled?: boolean
          params?: Json
          rule_key: string
          updated_at?: string
        }
        Update: {
          description?: string
          enabled?: boolean
          params?: Json
          rule_key?: string
          updated_at?: string
        }
        Relationships: []
      }
      tasks: {
        Row: {
          completed_at: string | null
          created_at: string
          customer_key: string | null
          due_date: string | null
          id: number
          status: string
          title: string
          user_id: string
        }
        Insert: {
          completed_at?: string | null
          created_at?: string
          customer_key?: string | null
          due_date?: string | null
          id?: never
          status?: string
          title: string
          user_id?: string
        }
        Update: {
          completed_at?: string | null
          created_at?: string
          customer_key?: string | null
          due_date?: string | null
          id?: never
          status?: string
          title?: string
          user_id?: string
        }
        Relationships: []
      }
      visits: {
        Row: {
          action_id: number | null
          comments: string | null
          competition_seen: string[]
          competitor_promos: string | null
          created_at: string
          customer_key: string
          display_quality: number | null
          id: number
          inventory_level: string | null
          staff_knowledge: number | null
          store_condition: number | null
          store_traffic: string | null
          user_id: string
          visit_date: string
          visit_type: string
        }
        Insert: {
          action_id?: number | null
          comments?: string | null
          competition_seen?: string[]
          competitor_promos?: string | null
          created_at?: string
          customer_key: string
          display_quality?: number | null
          id?: never
          inventory_level?: string | null
          staff_knowledge?: number | null
          store_condition?: number | null
          store_traffic?: string | null
          user_id?: string
          visit_date?: string
          visit_type: string
        }
        Update: {
          action_id?: number | null
          comments?: string | null
          competition_seen?: string[]
          competitor_promos?: string | null
          created_at?: string
          customer_key?: string
          display_quality?: number | null
          id?: never
          inventory_level?: string | null
          staff_knowledge?: number | null
          store_condition?: number | null
          store_traffic?: string | null
          user_id?: string
          visit_date?: string
          visit_type?: string
        }
        Relationships: []
      }
    }
    Views: {
      account_coverage: {
        Row: {
          contacted_last_30d: boolean | null
          contacted_last_90d: boolean | null
          customer_key: string | null
          last_contact_date: string | null
          rep_name: string | null
          user_id: string | null
        }
        Relationships: []
      }
      mission_batch_progress: {
        Row: {
          acted_count: number | null
          batch_id: number | null
          closed_count: number | null
          created_at: string | null
          created_by: string | null
          description: string | null
          dismissed_count: number | null
          due_date: string | null
          open_count: number | null
          overdue_count: number | null
          requires_visit: boolean | null
          scope_type: string | null
          scope_value: string | null
          title: string | null
          total: number | null
        }
        Relationships: []
      }
      rep_execution_summary: {
        Row: {
          actions_last_30d: number | null
          active: boolean | null
          assigned_accounts: number | null
          full_name: string | null
          last_action_date: string | null
          last_login_at: string | null
          open_recommendations: number | null
          overdue_recommendations: number | null
          rep_group_vendor_id: string | null
          user_id: string | null
        }
        Relationships: []
      }
      v_account_recent_orders: {
        Row: {
          backlog_qty: number | null
          bookings: number | null
          customer_key: string | null
          is_backlog_line: boolean | null
          line_num: number | null
          line_status_desc: string | null
          order_date: string | null
          order_id: string | null
          order_qty: number | null
          order_state: string | null
          order_status_desc: string | null
          part_description: string | null
          part_id: string | null
          part_key: string | null
          promise_date: string | null
        }
        Relationships: []
      }
      v_account_recent_shipments: {
        Row: {
          actual_delivery_date: string | null
          customer_key: string | null
          invoice_id: string | null
          line_num: number | null
          order_id: string | null
          packlist_id: string | null
          part_description: string | null
          part_id: string | null
          part_key: string | null
          promise_date: string | null
          ship_date: string | null
          shipment_state: string | null
          shipped_qty: number | null
          shipped_revenue: number | null
          shipper_status_desc: string | null
        }
        Relationships: []
      }
      v_account_revenue_monthly: {
        Row: {
          customer_key: string | null
          invoice_count: number | null
          month: string | null
          revenue: number | null
        }
        Relationships: []
      }
      v_account_summary: {
        Row: {
          backlog_qty: number | null
          customer_key: string | null
          last_invoice_date: string | null
          last_order_date: string | null
          open_order_count: number | null
          open_order_value: number | null
          revenue_prior_ytd: number | null
          revenue_trailing_12m: number | null
          revenue_ytd: number | null
        }
        Relationships: []
      }
      v_mission_detail: {
        Row: {
          batch_id: number | null
          closed_at: string | null
          customer_key: string | null
          customer_name: string | null
          due_date: string | null
          id: number | null
          outcome: string | null
          outcome_note: string | null
          priority: string | null
          rep_names: string | null
          requires_visit: boolean | null
          status: string | null
          title: string | null
        }
        Relationships: []
      }
      v_rep_activity: {
        Row: {
          actions_30d: number | null
          active: boolean | null
          email: string | null
          full_name: string | null
          last_action_date: string | null
          last_login_at: string | null
          logins_30d: number | null
          open_missions: number | null
          overdue_missions: number | null
          sales_rep_key: string | null
          user_id: string | null
          vendor_id: string | null
        }
        Relationships: []
      }
      v_user_accounts: {
        Row: {
          customer_key: string | null
          user_id: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      create_mission: {
        Args: {
          p_title: string
          p_reason?: string | null
          p_priority?: string
          p_due_date?: string | null
          p_requires_visit?: boolean
          p_scope_type?: string
          p_scope_value?: string | null
          p_customer_keys?: string[] | null
          p_active_only?: boolean
          p_dry_run?: boolean
        }
        Returns: {
          batch_id: number | null
          created_count: number
        }[]
      }
      generate_recommendations: {
        Args: never
        Returns: {
          out_created: number
          out_rule_key: string
        }[]
      }
      has_account_access: { Args: { p_customer_key: string }; Returns: boolean }
      is_admin: { Args: never; Returns: boolean }
      log_job_run: {
        Args: {
          p_error?: string
          p_job_name: string
          p_rows: number
          p_started_at?: string
          p_status: string
        }
        Returns: undefined
      }
      log_login: { Args: never; Returns: undefined }
      my_customer_keys: { Args: never; Returns: string[] }
      placeholder_rep_keys: { Args: never; Returns: string[] }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database['public']

export type Tables<T extends keyof (PublicSchema['Tables'] & PublicSchema['Views'])> =
  (PublicSchema['Tables'] & PublicSchema['Views'])[T] extends { Row: infer R } ? R : never

export type TablesInsert<T extends keyof PublicSchema['Tables']> =
  PublicSchema['Tables'][T] extends { Insert: infer I } ? I : never

export type TablesUpdate<T extends keyof PublicSchema['Tables']> =
  PublicSchema['Tables'][T] extends { Update: infer U } ? U : never
