/**
 * Generated by the Supabase MCP `generate_typescript_types` tool against the
 * portal project. DO NOT EDIT BY HAND — regenerate after every migration:
 *
 *   supabase gen types typescript --project-id <ref> > src/types/database.types.ts
 *
 * Note: only the `public` schema is present. The `erp` schema will appear here
 * once it is added to Settings → API → Exposed schemas (see supabase/README.md
 * post-migration checklist). Until then, `erp` reads are typed loosely by hand
 * in src/types/erp.ts.
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: '14.15'
  }
  public: {
    Tables: {
      account_assignments: {
        Row: {
          access: string
          assigned_by: string | null
          created_at: string
          customer_key: string
          id: number
          user_id: string
        }
        Insert: {
          access?: string
          assigned_by?: string | null
          created_at?: string
          customer_key: string
          id?: never
          user_id: string
        }
        Update: {
          access?: string
          assigned_by?: string | null
          created_at?: string
          customer_key?: string
          id?: never
          user_id?: string
        }
        Relationships: []
      }
      actions: {
        Row: {
          action_date: string
          action_type: string
          created_at: string
          customer_key: string
          id: number
          note: string | null
          recommendation_id: number | null
          user_id: string
        }
        Insert: {
          action_date?: string
          action_type: string
          created_at?: string
          customer_key: string
          id?: never
          note?: string | null
          recommendation_id?: number | null
          user_id?: string
        }
        Update: {
          action_date?: string
          action_type?: string
          created_at?: string
          customer_key?: string
          id?: never
          note?: string | null
          recommendation_id?: number | null
          user_id?: string
        }
        Relationships: []
      }
      ai_summaries: {
        Row: {
          content: string
          context_hash: string | null
          customer_key: string
          generated_at: string
          generated_by: string | null
          model: string | null
          prompt_version: string | null
        }
        Insert: {
          content: string
          context_hash?: string | null
          customer_key: string
          generated_at?: string
          generated_by?: string | null
          model?: string | null
          prompt_version?: string | null
        }
        Update: {
          content?: string
          context_hash?: string | null
          customer_key?: string
          generated_at?: string
          generated_by?: string | null
          model?: string | null
          prompt_version?: string | null
        }
        Relationships: []
      }
      contacts: {
        Row: {
          created_at: string
          created_by: string
          customer_key: string
          email: string | null
          id: number
          is_primary: boolean
          name: string
          notes: string | null
          phone: string | null
          title: string | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          created_by?: string
          customer_key: string
          email?: string | null
          id?: never
          is_primary?: boolean
          name: string
          notes?: string | null
          phone?: string | null
          title?: string | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          created_by?: string
          customer_key?: string
          email?: string | null
          id?: never
          is_primary?: boolean
          name?: string
          notes?: string | null
          phone?: string | null
          title?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      login_events: {
        Row: {
          id: number
          logged_at: string
          user_id: string
        }
        Insert: {
          id?: never
          logged_at?: string
          user_id: string
        }
        Update: {
          id?: never
          logged_at?: string
          user_id?: string
        }
        Relationships: []
      }
      notes: {
        Row: {
          body: string
          created_at: string
          created_by: string
          customer_key: string
          id: number
        }
        Insert: {
          body: string
          created_at?: string
          created_by?: string
          customer_key: string
          id?: never
        }
        Update: {
          body?: string
          created_at?: string
          created_by?: string
          customer_key?: string
          id?: never
        }
        Relationships: []
      }
      photos: {
        Row: {
          caption: string | null
          category: string | null
          created_at: string
          created_by: string
          customer_key: string
          id: number
          storage_path: string
          visit_id: number | null
        }
        Insert: {
          caption?: string | null
          category?: string | null
          created_at?: string
          created_by?: string
          customer_key: string
          id?: never
          storage_path: string
          visit_id?: number | null
        }
        Update: {
          caption?: string | null
          category?: string | null
          created_at?: string
          created_by?: string
          customer_key?: string
          id?: never
          storage_path?: string
          visit_id?: number | null
        }
        Relationships: []
      }
      profiles: {
        Row: {
          active: boolean
          created_at: string
          full_name: string
          rep_group_vendor_id: string | null
          role: string
          sales_rep_key: string | null
          user_id: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          full_name?: string
          rep_group_vendor_id?: string | null
          role?: string
          sales_rep_key?: string | null
          user_id: string
        }
        Update: {
          active?: boolean
          created_at?: string
          full_name?: string
          rep_group_vendor_id?: string | null
          role?: string
          sales_rep_key?: string | null
          user_id?: string
        }
        Relationships: []
      }
      recommendations: {
        Row: {
          closed_at: string | null
          closed_by: string | null
          created_at: string
          created_by: string | null
          customer_key: string
          due_date: string | null
          id: number
          outcome: string | null
          outcome_note: string | null
          priority: string
          reason: string | null
          rule_key: string | null
          source: string
          status: string
          title: string
        }
        Insert: {
          closed_at?: string | null
          closed_by?: string | null
          created_at?: string
          created_by?: string | null
          customer_key: string
          due_date?: string | null
          id?: never
          outcome?: string | null
          outcome_note?: string | null
          priority?: string
          reason?: string | null
          rule_key?: string | null
          source?: string
          status?: string
          title: string
        }
        Update: {
          closed_at?: string | null
          closed_by?: string | null
          created_at?: string
          created_by?: string | null
          customer_key?: string
          due_date?: string | null
          id?: never
          outcome?: string | null
          outcome_note?: string | null
          priority?: string
          reason?: string | null
          rule_key?: string | null
          source?: string
          status?: string
          title?: string
        }
        Relationships: []
      }
      rule_settings: {
        Row: {
          description: string
          enabled: boolean
          params: Json
          rule_key: string
          updated_at: string
        }
        Insert: {
          description: string
          enabled?: boolean
          params?: Json
          rule_key: string
          updated_at?: string
        }
        Update: {
          description?: string
          enabled?: boolean
          params?: Json
          rule_key?: string
          updated_at?: string
        }
        Relationships: []
      }
      tasks: {
        Row: {
          completed_at: string | null
          created_at: string
          customer_key: string | null
          due_date: string | null
          id: number
          status: string
          title: string
          user_id: string
        }
        Insert: {
          completed_at?: string | null
          created_at?: string
          customer_key?: string | null
          due_date?: string | null
          id?: never
          status?: string
          title: string
          user_id?: string
        }
        Update: {
          completed_at?: string | null
          created_at?: string
          customer_key?: string | null
          due_date?: string | null
          id?: never
          status?: string
          title?: string
          user_id?: string
        }
        Relationships: []
      }
      visits: {
        Row: {
          action_id: number | null
          comments: string | null
          competition_seen: string[]
          competitor_promos: string | null
          created_at: string
          customer_key: string
          display_quality: number | null
          id: number
          inventory_level: string | null
          staff_knowledge: number | null
          store_condition: number | null
          store_traffic: string | null
          user_id: string
          visit_date: string
          visit_type: string
        }
        Insert: {
          action_id?: number | null
          comments?: string | null
          competition_seen?: string[]
          competitor_promos?: string | null
          created_at?: string
          customer_key: string
          display_quality?: number | null
          id?: never
          inventory_level?: string | null
          staff_knowledge?: number | null
          store_condition?: number | null
          store_traffic?: string | null
          user_id?: string
          visit_date?: string
          visit_type: string
        }
        Update: {
          action_id?: number | null
          comments?: string | null
          competition_seen?: string[]
          competitor_promos?: string | null
          created_at?: string
          customer_key?: string
          display_quality?: number | null
          id?: never
          inventory_level?: string | null
          staff_knowledge?: number | null
          store_condition?: number | null
          store_traffic?: string | null
          user_id?: string
          visit_date?: string
          visit_type?: string
        }
        Relationships: []
      }
    }
    Views: {
      account_coverage: {
        Row: {
          contacted_last_30d: boolean | null
          contacted_last_90d: boolean | null
          customer_key: string | null
          last_contact_date: string | null
          rep_name: string | null
          user_id: string | null
        }
        Relationships: []
      }
      rep_execution_summary: {
        Row: {
          actions_last_30d: number | null
          active: boolean | null
          assigned_accounts: number | null
          full_name: string | null
          last_action_date: string | null
          last_login_at: string | null
          open_recommendations: number | null
          overdue_recommendations: number | null
          rep_group_vendor_id: string | null
          user_id: string | null
        }
        Relationships: []
      }
      v_user_accounts: {
        Row: {
          customer_key: string | null
          user_id: string | null
        }
        Relationships: []
      }
    }
    Functions: {
      generate_recommendations: {
        Args: never
        Returns: {
          created: number
          rule_key: string
        }[]
      }
      has_account_access: { Args: { p_customer_key: string }; Returns: boolean }
      is_admin: { Args: never; Returns: boolean }
      log_login: { Args: never; Returns: undefined }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type PublicSchema = Database['public']

export type Tables<T extends keyof (PublicSchema['Tables'] & PublicSchema['Views'])> =
  (PublicSchema['Tables'] & PublicSchema['Views'])[T] extends { Row: infer R } ? R : never

export type TablesInsert<T extends keyof PublicSchema['Tables']> =
  PublicSchema['Tables'][T] extends { Insert: infer I } ? I : never

export type TablesUpdate<T extends keyof PublicSchema['Tables']> =
  PublicSchema['Tables'][T] extends { Update: infer U } ? U : never
