"""
SQL Server bi.vw_* -> Supabase Postgres erp.* push.

Stage-and-swap, one short swap transaction per table, so readers never see a
half-loaded table and never wait on one either. Runs the rollup refresh,
scoring and QC steps after the last load, then logs one 'etl:run' row that
the portal's freshness stamp reads.

Usage:
    python push_to_supabase.py            # all tables in views.yml
    python push_to_supabase.py dim_customer fact_invoice_line   # subset

Environment (see .env.example):
    MSSQL_CONN   ODBC connection string to the SQL Server instance (VECA)
    PG_CONN      Postgres connection string to Supabase
                 (use the direct/session pooler connection, role: postgres)
    ETL_MIN_ROW_RATIO
                 Refuse a load that returns fewer than this fraction of the
                 rows the previous successful load of the same table had
                 (default 0.5). 0 disables the floor — for a known shrink.
"""

from __future__ import annotations

import io
import os
import re
import sys
import time
from datetime import datetime, timezone

import pyodbc
import psycopg
import yaml

from dotenv import load_dotenv

load_dotenv()

HERE = os.path.dirname(os.path.abspath(__file__))
BATCH_ROWS = 50_000

# Where a table lands before it is swapped into erp.* — a schema PostgREST
# does not expose and no app role can read (migration 20260901190400).
STAGE_SCHEMA = "etl_stage"


class LoadRefused(Exception):
    """A load that would have replaced good data with bad. Nothing was swapped."""


def load_config() -> dict:
    with open(os.path.join(HERE, "views.yml"), encoding="utf-8") as f:
        return yaml.safe_load(f)


def to_snake(name: str, overrides: dict[str, str]) -> str:
    if name in overrides:
        return overrides[name]
    s = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name)
    s = re.sub(r"(?<=[A-Z])(?=[A-Z][a-z])", "_", s)
    return s.lower()


def csv_field(v) -> str:
    if v is None:
        return ""
    if isinstance(v, bool):
        return "t" if v else "f"
    s = str(v)
    if any(c in s for c in (",", '"', "\n", "\r")):
        s = '"' + s.replace('"', '""') + '"'
    return s


def post_load_http(call):
    """Fire a post-load Edge Function, e.g. the nightly AI summary batch.

    Deliberately best-effort: the ERP data is loaded and the recommendations
    are generated by the time this runs, so a summary batch that fails — or a
    missing secret on a dev box — must not mark the whole load failed. It logs
    loudly and moves on; the function is idempotent and the next run picks up
    whatever it missed.

    Kept here rather than in pg_cron + pg_net because this is already the
    sanctioned nightly hook and it already knows every table loaded cleanly
    (TECH_STACK §4.2). A separate schedule is a second thing to drift.
    """
    import json
    import urllib.error
    import urllib.request

    name = call["function"]
    base = os.environ.get("SUPABASE_URL", "").rstrip("/")
    secret = os.environ.get("AI_BATCH_SECRET", "")
    if not base or not secret:
        print(f"post_load_http: skipping {name} — SUPABASE_URL/AI_BATCH_SECRET not set",
              file=sys.stderr)
        return

    body = json.dumps(call.get("body") or {}).encode()
    req = urllib.request.Request(
        f"{base}/functions/v1/{name}",
        data=body,
        headers={"content-type": "application/json", "x-batch-secret": secret},
        method="POST",
    )
    try:
        # Generous: the batch makes a few dozen model calls before replying.
        with urllib.request.urlopen(req, timeout=900) as res:
            print(f"post_load_http: {name} -> {res.read().decode()[:400]}")
    except urllib.error.HTTPError as exc:
        print(f"post_load_http: {name} FAILED {exc.code} — {exc.read().decode()[:400]}",
              file=sys.stderr)
    except Exception as exc:
        print(f"post_load_http: {name} FAILED — {exc}", file=sys.stderr)


def log_job_run(pg, job_name, started_at, status, rows=None, error=None):
    try:
        with pg.transaction():
            pg.execute(
                "select public.log_job_run(%s, %s, %s, %s, %s)",
                (job_name, status, rows, error, started_at),
            )
    except Exception as exc:  # audit failure must not fail the load itself
        print(f"job_runs logging failed for {job_name}: {exc}", file=sys.stderr)


def last_good_rows(pg, job_name: str) -> int | None:
    row = pg.execute(
        """
        select rows_affected from public.job_runs
        where job_name = %s and status = 'success' and rows_affected is not null
        order by finished_at desc limit 1
        """,
        (job_name,),
    ).fetchone()
    pg.commit()
    return int(row[0]) if row else None


def min_row_ratio() -> float:
    try:
        return float(os.environ.get("ETL_MIN_ROW_RATIO", "0.5"))
    except ValueError:
        return 0.5


def push_table(ms, pg, source_view: str, target_table: str, overrides: dict,
               floor_rows: int | None) -> int:
    """Stream one view into a staging table, then swap it into the live one.

    Two transactions on purpose. The first holds only the staging table
    while it waits on SQL Server (tens of seconds for the big facts); the
    live table is untouched and readers are unaffected. The second is
    DELETE + INSERT … SELECT from the staging table — no ACCESS EXCLUSIVE
    lock, so a rep's query at 5 PM Mountain blocks on nothing and sees
    either yesterday's rows or tonight's, never a mix and never a lock
    timeout. (TRUNCATE would be faster, but it takes the exclusive lock
    for the whole local copy, and the authenticator role gives up after
    8 s.) Autovacuum reclaims the dead tuples nightly.
    """
    schema, name = target_table.split(".", 1)
    stage = f'{STAGE_SCHEMA}."{name}"'
    live = f'"{schema}"."{name}"'

    cur = ms.cursor()
    cur.execute(f"SELECT * FROM {source_view}")
    src_cols = [to_snake(d[0], overrides) for d in cur.description]
    col_list = ", ".join(f'"{c}"' for c in src_cols)

    total = 0
    with pg.transaction():
        pcur = pg.cursor()
        # Fresh each run so a column added to the live table by a migration
        # is picked up, not a stale staging shape from last night.
        pcur.execute(f"DROP TABLE IF EXISTS {stage}")
        pcur.execute(
            f"CREATE UNLOGGED TABLE {stage} (LIKE {live} INCLUDING DEFAULTS)"
        )
        copy_sql = (
            f"COPY {stage} ({col_list}) "
            f"FROM STDIN WITH (FORMAT csv, NULL '')"
        )
        with pcur.copy(copy_sql) as copy:
            while True:
                rows = cur.fetchmany(BATCH_ROWS)
                if not rows:
                    break
                buf = io.StringIO()
                for row in rows:
                    buf.write(",".join(csv_field(v) for v in row) + "\n")
                copy.write(buf.getvalue())
                total += len(rows)

    # A source view that comes back empty (or nearly) is a broken feed, not
    # a business event: committing it would zero every rollup and delete
    # every account signal downstream. Refuse before the swap.
    ratio = min_row_ratio()
    if floor_rows and ratio > 0 and total < floor_rows * ratio:
        raise LoadRefused(
            f"{target_table}: source returned {total} rows, last good load had "
            f"{floor_rows} (floor {ratio:.0%}). Live table left untouched. "
            f"Set ETL_MIN_ROW_RATIO=0 to force."
        )

    with pg.transaction():
        pcur = pg.cursor()
        pcur.execute(f"DELETE FROM {live}")
        # Generated columns (order_date, ship_date, …) are computed by
        # Postgres on insert — copy only the columns the source supplied.
        pcur.execute(f"INSERT INTO {live} ({col_list}) SELECT {col_list} FROM {stage}")
        pcur.execute(f"DROP TABLE {stage}")
    return total


def fmt_elapsed(seconds: float) -> str:
    m, s = divmod(int(round(seconds)), 60)
    h, m = divmod(m, 60)
    return f"{h}h {m}m {s}s" if h else f"{m}m {s}s"


def main() -> int:
    run_started = time.monotonic()
    run_started_at = datetime.now(timezone.utc)
    print(f"push started at {datetime.now():%Y-%m-%d %H:%M:%S}")

    cfg = load_config()
    overrides = cfg.get("column_map") or {}
    only = {a.lower() for a in sys.argv[1:]}

    tables = [
        t for t in cfg["tables"]
        if not only or t["target_table"].split(".")[-1] in only
    ]
    if not tables:
        print(f"No tables matched {sorted(only)}", file=sys.stderr)
        return 2

    ms = pyodbc.connect(os.environ["MSSQL_CONN"])
    pg = psycopg.connect(os.environ["PG_CONN"])

    failures: list[str] = []
    total_rows = 0
    for t in tables:
        started = time.monotonic()
        started_at = datetime.now(timezone.utc)
        job_name = f"etl:{t['target_table']}"
        try:
            floor_rows = last_good_rows(pg, job_name)
            n = push_table(ms, pg, t["source_view"], t["target_table"], overrides,
                           floor_rows)
            total_rows += n
            log_job_run(pg, job_name, started_at, "success", n)
            print(f"{t['target_table']}: {n} rows in {time.monotonic() - started:.1f}s")
        except Exception as exc:  # keep loading the rest; report at the end
            failures.append(f"{t['target_table']}: {exc}")
            log_job_run(pg, job_name, started_at, "error", None, str(exc))
            print(f"{t['target_table']}: FAILED — {exc}", file=sys.stderr)

    # Post-load only when every table landed and this was a full run. A
    # partial load must not refresh rollups over a mix of old and new facts.
    if not failures and not only:
        for sql in cfg.get("post_load_sql") or []:
            step_started = time.monotonic()
            step_started_at = datetime.now(timezone.utc)
            try:
                with pg.transaction():
                    res = pg.execute(sql).fetchall()
                print(f"post_load: {sql} -> {res} "
                      f"({time.monotonic() - step_started:.1f}s)")
            except Exception as exc:
                # Stop here: later steps read what this one should have
                # produced (views.yml explains the ordering).
                failures.append(f"post_load: {sql}: {exc}")
                log_job_run(pg, "etl:post_load", step_started_at, "error", None,
                            f"{sql}: {exc}")
                print(f"post_load: {sql} FAILED — {exc}", file=sys.stderr)
                break

        if not failures:
            for call in cfg.get("post_load_http") or []:
                post_load_http(call)

    # The one row the freshness stamp reads (20260901190400): success means
    # every table loaded AND every post-load step ran. A subset run is
    # never a full refresh, so it is logged but never as 'etl:run' success.
    if not only:
        log_job_run(
            pg, "etl:run", run_started_at,
            "success" if not failures else "error",
            total_rows if not failures else None,
            "; ".join(failures) if failures else None,
        )

    ms.close()
    pg.close()

    print(f"push finished at {datetime.now():%Y-%m-%d %H:%M:%S} "
          f"— elapsed {fmt_elapsed(time.monotonic() - run_started)}"
          + (f" (with {len(failures)} failure(s))" if failures else ""))
    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
