/*============================================================================
  ai-summary-batch

  Pre-generates account briefings overnight so the top of a rep's Today list
  carries a real summary instead of a formula-built sentence.

  Justification for existing at all (TECH_STACK §3.2, and the bar set in
  functions/README.md): it holds OPENAI_API_KEY. A Postgres function cannot.

  ── THIS FUNCTION USES service_role. Here is why that is not the thing the
     architecture forbids. ────────────────────────────────────────────────

  ai-account-summary's header is emphatic that it must never import
  serviceClient(), and it must not. But read the invariant precisely: the ban
  is on a server reading account data ON BEHALF OF A REP and handing back the
  result, because that moves the access decision out of Postgres and into
  TypeScript, where it eventually leaks.

  A nightly batch has no caller. It answers no browser, returns no account
  data — only counts — and writes rows to public.ai_summaries, whose read
  path is still `customer_key in (select public.my_customer_keys())`. A
  summary written for an account outside a rep's book is invisible to that
  rep, enforced by the same policy that protects everything else.

  ── The subtlety that makes it safe, and would have been the leak if it were
     false ────────────────────────────────────────────────────────────────

  buildContext() reads notes, visits, actions and recommendations filtered
  only by customer_key. Under service_role those reads are unscoped. That is
  acceptable ONLY because every one of those policies is ACCOUNT-scoped, not
  AUTHOR-scoped: any rep who can see the account can already see all of its
  notes. So the batch context is byte-identical to what the assigned rep
  would have built themselves — which is also what keeps the shared context
  hash meaningful across both paths.

  If a per-author policy is ever added to public.notes, that equivalence
  breaks and this function must be revisited.

  ── The guards, all five ───────────────────────────────────────────────────

  1. No JWT path at all. A constant-time match on x-batch-secret against
     AI_BATCH_SECRET, and nothing else gets in. requireCaller() is never
     called; there is no user here.
  2. It cannot be pointed at an account. The request body carries no
     customer_key — targets come only from public.ai_batch_targets(). Even
     with a leaked secret this is not an exfiltration oracle: it returns
     counts, never account data.
  3. Hard caps: AI_BATCH_MAX_ACCOUNTS, bounded concurrency, per-account
     try/catch so one failure cannot take down the run, and a job_runs row.
  4. generated_by = null, so batch rows are distinguishable from
     rep-triggered ones and never consume anyone's daily allowance.
  5. service_role is used for exactly two things: calling ai_batch_targets()
     and upserting ai_summaries. Context building goes through the same
     shared module the interactive path uses.

  Rejected alternative: minting JWTs to impersonate each rep. It needs the
  JWT secret, attributes audit rows to people who did nothing, and STILL puts
  the access decision in TypeScript — strictly worse than an honest,
  documented, narrow exception.

  ── Invoking it ────────────────────────────────────────────────────────────
      curl -X POST "$SUPABASE_URL/functions/v1/ai-summary-batch" \
        -H "x-batch-secret: $AI_BATCH_SECRET" \
        -H 'content-type: application/json' -d '{"per_rep":5}'
============================================================================*/

import { fail, json, preflight } from '../_shared/cors.ts'
import { HttpError, readJson, requirePost, serviceClient } from '../_shared/supabase.ts'
import {
  callOpenAI,
  envInt,
  MODEL,
  prepareContext,
  PROMPT_VERSION,
} from '../_shared/aiSummary.ts'

const DEFAULT_PER_REP = envInt('AI_BATCH_PER_REP', 5)
const MAX_ACCOUNTS = envInt('AI_BATCH_MAX_ACCOUNTS', 100)
const CONCURRENCY = Math.max(1, envInt('AI_BATCH_CONCURRENCY', 3))

/**
 * Skip an account whose summary is already younger than this. The context
 * hash makes an unchanged account free anyway, but this avoids even building
 * the context for the ones a rep regenerated by hand this morning.
 */
const MIN_AGE_HOURS = envInt('AI_BATCH_MIN_AGE_HOURS', 20)

/**
 * Timing-safe compare. `===` on secrets leaks length and prefix through
 * response timing; it is one function to avoid that, so avoid it.
 */
function secretMatches(provided: string, expected: string): boolean {
  if (provided.length !== expected.length) return false
  let diff = 0
  for (let i = 0; i < provided.length; i++) {
    diff |= provided.charCodeAt(i) ^ expected.charCodeAt(i)
  }
  return diff === 0
}

type RequestBody = { per_rep?: number; max_accounts?: number }

type Outcome = 'generated' | 'cached' | 'skipped' | 'insufficient' | 'failed'

async function generateFor(
  client: ReturnType<typeof serviceClient>,
  customerKey: string,
): Promise<Outcome> {
  const existing = await client
    .from('ai_summaries')
    .select('context_hash, generated_at')
    .eq('customer_key', customerKey)
    .maybeSingle()

  const row = existing.data as { context_hash: string | null; generated_at: string } | null

  if (row && MIN_AGE_HOURS > 0) {
    const ageHours = (Date.now() - new Date(row.generated_at).getTime()) / 3_600_000
    if (ageHours >= 0 && ageHours < MIN_AGE_HOURS) return 'skipped'
  }

  const prepared = await prepareContext(client, customerKey)
  if (prepared.insufficient) return 'insufficient'

  // Unchanged since last time → nothing to pay for.
  if (row && row.context_hash === prepared.contextHash) return 'cached'

  const briefing = await callOpenAI(prepared.contextJson)

  const { error } = await client.from('ai_summaries').upsert(
    {
      customer_key: customerKey,
      content: briefing.briefing,
      headline: briefing.headline || null,
      model: MODEL,
      context_hash: prepared.contextHash,
      prompt_version: PROMPT_VERSION,
      generated_at: new Date().toISOString(),
      // Not attributed to a person: nobody asked for it, and it must not
      // count against anyone's daily cap.
      generated_by: null,
    },
    { onConflict: 'customer_key' },
  )
  if (error) throw error

  return 'generated'
}

/** Fixed-size worker pool. Deliberately not Promise.all over the whole list:
    100 concurrent OpenAI calls is how a nightly job earns a rate limit. */
async function runPool(
  keys: string[],
  worker: (key: string) => Promise<Outcome>,
  size: number,
): Promise<Record<Outcome, number>> {
  const tally: Record<Outcome, number> = {
    generated: 0, cached: 0, skipped: 0, insufficient: 0, failed: 0,
  }
  let next = 0

  async function pump(): Promise<void> {
    while (next < keys.length) {
      const key = keys[next++]
      try {
        tally[await worker(key)] += 1
      } catch (err) {
        // One bad account must not end the run — the other ninety-nine reps
        // still want their briefings in the morning.
        tally.failed += 1
        console.error('batch: account failed', key, err)
      }
    }
  }

  await Promise.all(Array.from({ length: Math.min(size, keys.length) }, () => pump()))
  return tally
}

async function handle(req: Request): Promise<Response> {
  requirePost(req)

  const expected = Deno.env.get('AI_BATCH_SECRET') ?? ''
  if (!expected) {
    throw new HttpError(500, 'missing_env',
      'AI_BATCH_SECRET is not set on this function. Refusing to run unauthenticated.')
  }
  const provided = req.headers.get('x-batch-secret') ?? ''
  if (!secretMatches(provided, expected)) {
    throw new HttpError(401, 'bad_secret', 'Invalid batch secret.')
  }

  const body = await readJson<RequestBody>(req).catch(() => ({}) as RequestBody)
  const perRep = Math.max(1, Math.min(Number(body.per_rep) || DEFAULT_PER_REP, 25))
  const cap = Math.max(1, Math.min(Number(body.max_accounts) || MAX_ACCOUNTS, 500))

  const client = serviceClient()
  const started = new Date().toISOString()

  const targets = await client.rpc('ai_batch_targets', { p_per_rep: perRep })
  if (targets.error) {
    console.error('ai_batch_targets failed', targets.error)
    throw new HttpError(500, 'targets_failed', 'Could not resolve the target accounts.')
  }

  const all = ((targets.data ?? []) as { customer_key: string }[]).map((r) => r.customer_key)
  const keys = all.slice(0, cap)
  // Never let a cap silently look like full coverage.
  if (all.length > keys.length) {
    console.warn(`batch: capped at ${keys.length} of ${all.length} target accounts`)
  }

  const tally = await runPool(keys, (k) => generateFor(client, k), CONCURRENCY)

  const summary = {
    targets: all.length,
    attempted: keys.length,
    ...tally,
  }
  console.log('batch complete', summary)

  await client.rpc('log_job_run', {
    p_job_name: 'ai_summary_batch',
    p_status: tally.failed > 0 && tally.generated === 0 ? 'error' : 'success',
    p_rows: tally.generated,
    p_error: tally.failed > 0 ? `${tally.failed} accounts failed` : null,
    p_started_at: started,
  })

  return json(summary)
}

Deno.serve(async (req) => {
  const pre = preflight(req)
  if (pre) return pre

  try {
    return await handle(req)
  } catch (err) {
    if (err instanceof HttpError) {
      return fail(err.status, err.code, err.message)
    }
    console.error('ai-summary-batch unhandled error', err)
    return fail(500, 'internal_error', 'The batch run failed.')
  }
})
